//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryPrinter.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LotterData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LotterData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.DateTime MyDateTimeField;
        
        private int AgentIDField;
        
        private decimal MoneyField;
        
        private int ZhuShuField;
        
        private int MultipleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifiersField;
        
        private int SendsField;
        
        private System.DateTime HandleDateTimeField;
        
        private int HandleResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HandleDescriptionField;
        
        private System.DateTime EndTimeField;
        
        private int IsOpenedField;
        
        private decimal WinMoneyField;
        
        private decimal WinMoneyNoWithTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinDescriptionField;
        
        private int QuashStatusField;
        
        private int LotteryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrikeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintDescriptionField;
        
        private System.DateTime PrintDateTimeField;
        
        private System.DateTime PringHandleDateTimeField;
        
        private int PrintOutTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TouZhuSPValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueNameField;
        
        private int TotalStatusField;
        
        private int OpenedStatusField;
        
        private int IsBackMoneyField;
        
        private int IsJiaJiangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNoField;
        
        private int PlayTypeIDField;
        
        private int TdescField;
        
        private int WinnerStatusField;
        
        private int PrizeStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        private int RecvsField;
        
        private int SplitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SplitedParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIdentifierField;
        
        private System.DateTime OpenTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchemeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromSourceField;
        
        private int PushStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime MyDateTime {
            get {
                return this.MyDateTimeField;
            }
            set {
                if ((this.MyDateTimeField.Equals(value) != true)) {
                    this.MyDateTimeField = value;
                    this.RaisePropertyChanged("MyDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((this.AgentIDField.Equals(value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ZhuShu {
            get {
                return this.ZhuShuField;
            }
            set {
                if ((this.ZhuShuField.Equals(value) != true)) {
                    this.ZhuShuField = value;
                    this.RaisePropertyChanged("ZhuShu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Multiple {
            get {
                return this.MultipleField;
            }
            set {
                if ((this.MultipleField.Equals(value) != true)) {
                    this.MultipleField = value;
                    this.RaisePropertyChanged("Multiple");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Identifiers {
            get {
                return this.IdentifiersField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifiersField, value) != true)) {
                    this.IdentifiersField = value;
                    this.RaisePropertyChanged("Identifiers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Sends {
            get {
                return this.SendsField;
            }
            set {
                if ((this.SendsField.Equals(value) != true)) {
                    this.SendsField = value;
                    this.RaisePropertyChanged("Sends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime HandleDateTime {
            get {
                return this.HandleDateTimeField;
            }
            set {
                if ((this.HandleDateTimeField.Equals(value) != true)) {
                    this.HandleDateTimeField = value;
                    this.RaisePropertyChanged("HandleDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int HandleResult {
            get {
                return this.HandleResultField;
            }
            set {
                if ((this.HandleResultField.Equals(value) != true)) {
                    this.HandleResultField = value;
                    this.RaisePropertyChanged("HandleResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string HandleDescription {
            get {
                return this.HandleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.HandleDescriptionField, value) != true)) {
                    this.HandleDescriptionField = value;
                    this.RaisePropertyChanged("HandleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int IsOpened {
            get {
                return this.IsOpenedField;
            }
            set {
                if ((this.IsOpenedField.Equals(value) != true)) {
                    this.IsOpenedField = value;
                    this.RaisePropertyChanged("IsOpened");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public decimal WinMoney {
            get {
                return this.WinMoneyField;
            }
            set {
                if ((this.WinMoneyField.Equals(value) != true)) {
                    this.WinMoneyField = value;
                    this.RaisePropertyChanged("WinMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public decimal WinMoneyNoWithTax {
            get {
                return this.WinMoneyNoWithTaxField;
            }
            set {
                if ((this.WinMoneyNoWithTaxField.Equals(value) != true)) {
                    this.WinMoneyNoWithTaxField = value;
                    this.RaisePropertyChanged("WinMoneyNoWithTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string WinDescription {
            get {
                return this.WinDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.WinDescriptionField, value) != true)) {
                    this.WinDescriptionField = value;
                    this.RaisePropertyChanged("WinDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int QuashStatus {
            get {
                return this.QuashStatusField;
            }
            set {
                if ((this.QuashStatusField.Equals(value) != true)) {
                    this.QuashStatusField = value;
                    this.RaisePropertyChanged("QuashStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int LotteryId {
            get {
                return this.LotteryIdField;
            }
            set {
                if ((this.LotteryIdField.Equals(value) != true)) {
                    this.LotteryIdField = value;
                    this.RaisePropertyChanged("LotteryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string StrikeDate {
            get {
                return this.StrikeDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StrikeDateField, value) != true)) {
                    this.StrikeDateField = value;
                    this.RaisePropertyChanged("StrikeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string PrintResult {
            get {
                return this.PrintResultField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintResultField, value) != true)) {
                    this.PrintResultField = value;
                    this.RaisePropertyChanged("PrintResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string PrintDescription {
            get {
                return this.PrintDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintDescriptionField, value) != true)) {
                    this.PrintDescriptionField = value;
                    this.RaisePropertyChanged("PrintDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public System.DateTime PrintDateTime {
            get {
                return this.PrintDateTimeField;
            }
            set {
                if ((this.PrintDateTimeField.Equals(value) != true)) {
                    this.PrintDateTimeField = value;
                    this.RaisePropertyChanged("PrintDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.DateTime PringHandleDateTime {
            get {
                return this.PringHandleDateTimeField;
            }
            set {
                if ((this.PringHandleDateTimeField.Equals(value) != true)) {
                    this.PringHandleDateTimeField = value;
                    this.RaisePropertyChanged("PringHandleDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int PrintOutTypeID {
            get {
                return this.PrintOutTypeIDField;
            }
            set {
                if ((this.PrintOutTypeIDField.Equals(value) != true)) {
                    this.PrintOutTypeIDField = value;
                    this.RaisePropertyChanged("PrintOutTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string TouZhuSPValues {
            get {
                return this.TouZhuSPValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.TouZhuSPValuesField, value) != true)) {
                    this.TouZhuSPValuesField = value;
                    this.RaisePropertyChanged("TouZhuSPValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string IssueName {
            get {
                return this.IssueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueNameField, value) != true)) {
                    this.IssueNameField = value;
                    this.RaisePropertyChanged("IssueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public int TotalStatus {
            get {
                return this.TotalStatusField;
            }
            set {
                if ((this.TotalStatusField.Equals(value) != true)) {
                    this.TotalStatusField = value;
                    this.RaisePropertyChanged("TotalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public int OpenedStatus {
            get {
                return this.OpenedStatusField;
            }
            set {
                if ((this.OpenedStatusField.Equals(value) != true)) {
                    this.OpenedStatusField = value;
                    this.RaisePropertyChanged("OpenedStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public int IsBackMoney {
            get {
                return this.IsBackMoneyField;
            }
            set {
                if ((this.IsBackMoneyField.Equals(value) != true)) {
                    this.IsBackMoneyField = value;
                    this.RaisePropertyChanged("IsBackMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public int IsJiaJiang {
            get {
                return this.IsJiaJiangField;
            }
            set {
                if ((this.IsJiaJiangField.Equals(value) != true)) {
                    this.IsJiaJiangField = value;
                    this.RaisePropertyChanged("IsJiaJiang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string TicketNo {
            get {
                return this.TicketNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNoField, value) != true)) {
                    this.TicketNoField = value;
                    this.RaisePropertyChanged("TicketNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=32)]
        public int PlayTypeID {
            get {
                return this.PlayTypeIDField;
            }
            set {
                if ((this.PlayTypeIDField.Equals(value) != true)) {
                    this.PlayTypeIDField = value;
                    this.RaisePropertyChanged("PlayTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=33)]
        public int Tdesc {
            get {
                return this.TdescField;
            }
            set {
                if ((this.TdescField.Equals(value) != true)) {
                    this.TdescField = value;
                    this.RaisePropertyChanged("Tdesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public int WinnerStatus {
            get {
                return this.WinnerStatusField;
            }
            set {
                if ((this.WinnerStatusField.Equals(value) != true)) {
                    this.WinnerStatusField = value;
                    this.RaisePropertyChanged("WinnerStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public int PrizeStatus {
            get {
                return this.PrizeStatusField;
            }
            set {
                if ((this.PrizeStatusField.Equals(value) != true)) {
                    this.PrizeStatusField = value;
                    this.RaisePropertyChanged("PrizeStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=37)]
        public int Recvs {
            get {
                return this.RecvsField;
            }
            set {
                if ((this.RecvsField.Equals(value) != true)) {
                    this.RecvsField = value;
                    this.RaisePropertyChanged("Recvs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=38)]
        public int Splited {
            get {
                return this.SplitedField;
            }
            set {
                if ((this.SplitedField.Equals(value) != true)) {
                    this.SplitedField = value;
                    this.RaisePropertyChanged("Splited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string SplitedParentID {
            get {
                return this.SplitedParentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SplitedParentIDField, value) != true)) {
                    this.SplitedParentIDField = value;
                    this.RaisePropertyChanged("SplitedParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string ParentIdentifier {
            get {
                return this.ParentIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIdentifierField, value) != true)) {
                    this.ParentIdentifierField = value;
                    this.RaisePropertyChanged("ParentIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=41)]
        public System.DateTime OpenTime {
            get {
                return this.OpenTimeField;
            }
            set {
                if ((this.OpenTimeField.Equals(value) != true)) {
                    this.OpenTimeField = value;
                    this.RaisePropertyChanged("OpenTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string SchemeNo {
            get {
                return this.SchemeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SchemeNoField, value) != true)) {
                    this.SchemeNoField = value;
                    this.RaisePropertyChanged("SchemeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string FromSource {
            get {
                return this.FromSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.FromSourceField, value) != true)) {
                    this.FromSourceField = value;
                    this.RaisePropertyChanged("FromSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=44)]
        public int PushStatus {
            get {
                return this.PushStatusField;
            }
            set {
                if ((this.PushStatusField.Equals(value) != true)) {
                    this.PushStatusField = value;
                    this.RaisePropertyChanged("PushStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 InputID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataMethod", ReplyAction="*")]
        LotteryPrinter.ServiceReference1.GetDataMethodResponse GetDataMethod(LotteryPrinter.ServiceReference1.GetDataMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.GetDataMethodResponse> GetDataMethodAsync(LotteryPrinter.ServiceReference1.GetDataMethodRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelectDataMethod", ReplyAction="*")]
        LotteryPrinter.ServiceReference1.DelectDataMethodResponse DelectDataMethod(LotteryPrinter.ServiceReference1.DelectDataMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelectDataMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.DelectDataMethodResponse> DelectDataMethodAsync(LotteryPrinter.ServiceReference1.DelectDataMethodRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectIDDataMethod", ReplyAction="*")]
        LotteryPrinter.ServiceReference1.SelectIDDataMethodResponse SelectIDDataMethod(LotteryPrinter.ServiceReference1.SelectIDDataMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectIDDataMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.SelectIDDataMethodResponse> SelectIDDataMethodAsync(LotteryPrinter.ServiceReference1.SelectIDDataMethodRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDataMethod", ReplyAction="*")]
        LotteryPrinter.ServiceReference1.SetDataMethodResponse SetDataMethod(LotteryPrinter.ServiceReference1.SetDataMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDataMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.SetDataMethodResponse> SetDataMethodAsync(LotteryPrinter.ServiceReference1.SetDataMethodRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upDate", ReplyAction="*")]
        LotteryPrinter.ServiceReference1.upDateResponse upDate(LotteryPrinter.ServiceReference1.upDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upDate", ReplyAction="*")]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.upDateResponse> upDateAsync(LotteryPrinter.ServiceReference1.upDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataMethod", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.GetDataMethodRequestBody Body;
        
        public GetDataMethodRequest() {
        }
        
        public GetDataMethodRequest(LotteryPrinter.ServiceReference1.GetDataMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InputID;
        
        public GetDataMethodRequestBody() {
        }
        
        public GetDataMethodRequestBody(string InputID) {
            this.InputID = InputID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.GetDataMethodResponseBody Body;
        
        public GetDataMethodResponse() {
        }
        
        public GetDataMethodResponse(LotteryPrinter.ServiceReference1.GetDataMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LotteryPrinter.ServiceReference1.LotterData GetDataMethodResult;
        
        public GetDataMethodResponseBody() {
        }
        
        public GetDataMethodResponseBody(LotteryPrinter.ServiceReference1.LotterData GetDataMethodResult) {
            this.GetDataMethodResult = GetDataMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelectDataMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelectDataMethod", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.DelectDataMethodRequestBody Body;
        
        public DelectDataMethodRequest() {
        }
        
        public DelectDataMethodRequest(LotteryPrinter.ServiceReference1.DelectDataMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelectDataMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public DelectDataMethodRequestBody() {
        }
        
        public DelectDataMethodRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelectDataMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelectDataMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.DelectDataMethodResponseBody Body;
        
        public DelectDataMethodResponse() {
        }
        
        public DelectDataMethodResponse(LotteryPrinter.ServiceReference1.DelectDataMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelectDataMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DelectDataMethodResult;
        
        public DelectDataMethodResponseBody() {
        }
        
        public DelectDataMethodResponseBody(int DelectDataMethodResult) {
            this.DelectDataMethodResult = DelectDataMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectIDDataMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectIDDataMethod", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.SelectIDDataMethodRequestBody Body;
        
        public SelectIDDataMethodRequest() {
        }
        
        public SelectIDDataMethodRequest(LotteryPrinter.ServiceReference1.SelectIDDataMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectIDDataMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public SelectIDDataMethodRequestBody() {
        }
        
        public SelectIDDataMethodRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectIDDataMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectIDDataMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.SelectIDDataMethodResponseBody Body;
        
        public SelectIDDataMethodResponse() {
        }
        
        public SelectIDDataMethodResponse(LotteryPrinter.ServiceReference1.SelectIDDataMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectIDDataMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SelectIDDataMethodResult;
        
        public SelectIDDataMethodResponseBody() {
        }
        
        public SelectIDDataMethodResponseBody(int SelectIDDataMethodResult) {
            this.SelectIDDataMethodResult = SelectIDDataMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataMethod", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.SetDataMethodRequestBody Body;
        
        public SetDataMethodRequest() {
        }
        
        public SetDataMethodRequest(LotteryPrinter.ServiceReference1.SetDataMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public SetDataMethodRequestBody() {
        }
        
        public SetDataMethodRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.SetDataMethodResponseBody Body;
        
        public SetDataMethodResponse() {
        }
        
        public SetDataMethodResponse(LotteryPrinter.ServiceReference1.SetDataMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SetDataMethodResult;
        
        public SetDataMethodResponseBody() {
        }
        
        public SetDataMethodResponseBody(int SetDataMethodResult) {
            this.SetDataMethodResult = SetDataMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class upDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="upDate", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.upDateRequestBody Body;
        
        public upDateRequest() {
        }
        
        public upDateRequest(LotteryPrinter.ServiceReference1.upDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class upDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public upDateRequestBody() {
        }
        
        public upDateRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class upDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="upDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public LotteryPrinter.ServiceReference1.upDateResponseBody Body;
        
        public upDateResponse() {
        }
        
        public upDateResponse(LotteryPrinter.ServiceReference1.upDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class upDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int upDateResult;
        
        public upDateResponseBody() {
        }
        
        public upDateResponseBody(int upDateResult) {
            this.upDateResult = upDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : LotteryPrinter.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<LotteryPrinter.ServiceReference1.Service1Soap>, LotteryPrinter.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotteryPrinter.ServiceReference1.GetDataMethodResponse LotteryPrinter.ServiceReference1.Service1Soap.GetDataMethod(LotteryPrinter.ServiceReference1.GetDataMethodRequest request) {
            return base.Channel.GetDataMethod(request);
        }
        
        public LotteryPrinter.ServiceReference1.LotterData GetDataMethod(string InputID) {
            LotteryPrinter.ServiceReference1.GetDataMethodRequest inValue = new LotteryPrinter.ServiceReference1.GetDataMethodRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.GetDataMethodRequestBody();
            inValue.Body.InputID = InputID;
            LotteryPrinter.ServiceReference1.GetDataMethodResponse retVal = ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).GetDataMethod(inValue);
            return retVal.Body.GetDataMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.GetDataMethodResponse> LotteryPrinter.ServiceReference1.Service1Soap.GetDataMethodAsync(LotteryPrinter.ServiceReference1.GetDataMethodRequest request) {
            return base.Channel.GetDataMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.GetDataMethodResponse> GetDataMethodAsync(string InputID) {
            LotteryPrinter.ServiceReference1.GetDataMethodRequest inValue = new LotteryPrinter.ServiceReference1.GetDataMethodRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.GetDataMethodRequestBody();
            inValue.Body.InputID = InputID;
            return ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).GetDataMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotteryPrinter.ServiceReference1.DelectDataMethodResponse LotteryPrinter.ServiceReference1.Service1Soap.DelectDataMethod(LotteryPrinter.ServiceReference1.DelectDataMethodRequest request) {
            return base.Channel.DelectDataMethod(request);
        }
        
        public int DelectDataMethod(string str) {
            LotteryPrinter.ServiceReference1.DelectDataMethodRequest inValue = new LotteryPrinter.ServiceReference1.DelectDataMethodRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.DelectDataMethodRequestBody();
            inValue.Body.str = str;
            LotteryPrinter.ServiceReference1.DelectDataMethodResponse retVal = ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).DelectDataMethod(inValue);
            return retVal.Body.DelectDataMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.DelectDataMethodResponse> LotteryPrinter.ServiceReference1.Service1Soap.DelectDataMethodAsync(LotteryPrinter.ServiceReference1.DelectDataMethodRequest request) {
            return base.Channel.DelectDataMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.DelectDataMethodResponse> DelectDataMethodAsync(string str) {
            LotteryPrinter.ServiceReference1.DelectDataMethodRequest inValue = new LotteryPrinter.ServiceReference1.DelectDataMethodRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.DelectDataMethodRequestBody();
            inValue.Body.str = str;
            return ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).DelectDataMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotteryPrinter.ServiceReference1.SelectIDDataMethodResponse LotteryPrinter.ServiceReference1.Service1Soap.SelectIDDataMethod(LotteryPrinter.ServiceReference1.SelectIDDataMethodRequest request) {
            return base.Channel.SelectIDDataMethod(request);
        }
        
        public int SelectIDDataMethod(string str) {
            LotteryPrinter.ServiceReference1.SelectIDDataMethodRequest inValue = new LotteryPrinter.ServiceReference1.SelectIDDataMethodRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.SelectIDDataMethodRequestBody();
            inValue.Body.str = str;
            LotteryPrinter.ServiceReference1.SelectIDDataMethodResponse retVal = ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).SelectIDDataMethod(inValue);
            return retVal.Body.SelectIDDataMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.SelectIDDataMethodResponse> LotteryPrinter.ServiceReference1.Service1Soap.SelectIDDataMethodAsync(LotteryPrinter.ServiceReference1.SelectIDDataMethodRequest request) {
            return base.Channel.SelectIDDataMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.SelectIDDataMethodResponse> SelectIDDataMethodAsync(string str) {
            LotteryPrinter.ServiceReference1.SelectIDDataMethodRequest inValue = new LotteryPrinter.ServiceReference1.SelectIDDataMethodRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.SelectIDDataMethodRequestBody();
            inValue.Body.str = str;
            return ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).SelectIDDataMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotteryPrinter.ServiceReference1.SetDataMethodResponse LotteryPrinter.ServiceReference1.Service1Soap.SetDataMethod(LotteryPrinter.ServiceReference1.SetDataMethodRequest request) {
            return base.Channel.SetDataMethod(request);
        }
        
        public int SetDataMethod(string str) {
            LotteryPrinter.ServiceReference1.SetDataMethodRequest inValue = new LotteryPrinter.ServiceReference1.SetDataMethodRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.SetDataMethodRequestBody();
            inValue.Body.str = str;
            LotteryPrinter.ServiceReference1.SetDataMethodResponse retVal = ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).SetDataMethod(inValue);
            return retVal.Body.SetDataMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.SetDataMethodResponse> LotteryPrinter.ServiceReference1.Service1Soap.SetDataMethodAsync(LotteryPrinter.ServiceReference1.SetDataMethodRequest request) {
            return base.Channel.SetDataMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.SetDataMethodResponse> SetDataMethodAsync(string str) {
            LotteryPrinter.ServiceReference1.SetDataMethodRequest inValue = new LotteryPrinter.ServiceReference1.SetDataMethodRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.SetDataMethodRequestBody();
            inValue.Body.str = str;
            return ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).SetDataMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotteryPrinter.ServiceReference1.upDateResponse LotteryPrinter.ServiceReference1.Service1Soap.upDate(LotteryPrinter.ServiceReference1.upDateRequest request) {
            return base.Channel.upDate(request);
        }
        
        public int upDate(string str) {
            LotteryPrinter.ServiceReference1.upDateRequest inValue = new LotteryPrinter.ServiceReference1.upDateRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.upDateRequestBody();
            inValue.Body.str = str;
            LotteryPrinter.ServiceReference1.upDateResponse retVal = ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).upDate(inValue);
            return retVal.Body.upDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.upDateResponse> LotteryPrinter.ServiceReference1.Service1Soap.upDateAsync(LotteryPrinter.ServiceReference1.upDateRequest request) {
            return base.Channel.upDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotteryPrinter.ServiceReference1.upDateResponse> upDateAsync(string str) {
            LotteryPrinter.ServiceReference1.upDateRequest inValue = new LotteryPrinter.ServiceReference1.upDateRequest();
            inValue.Body = new LotteryPrinter.ServiceReference1.upDateRequestBody();
            inValue.Body.str = str;
            return ((LotteryPrinter.ServiceReference1.Service1Soap)(this)).upDateAsync(inValue);
        }
    }
}
